<x-app-layout>
    <x-slot name="header">
        <div class="flex items-center justify-between">
            <div>
                <h2 class="text-2xl font-bold text-gray-800 leading-tight">{{ __('PIB') }}</h2>
            </div>
            <a href="{{ route('format.index') }}" class="inline-flex items-center justify-center rounded-xl bg-gray-600 px-4 py-2 text-sm font-semibold text-white hover:bg-gray-700">Kembali</a>
        </div>
    </x-slot>

    <div class="py-8">
        <form method="POST" action="{{ route('format.pib.save') }}">
            @csrf
            <div class="mx-auto max-w-6xl bg-white p-6 shadow-xl ring-1 ring-gray-200" style="font-family: Arial, sans-serif; color: #1f2937;">
            <div class="grid grid-cols-12 gap-3 border-b border-gray-300 pb-4">
                <div class="col-span-4 flex items-center gap-3"><div class="flex h-14 w-14 items-center justify-center rounded-full border-2 border-blue-900 bg-blue-50 text-2xl font-black text-blue-900">🐘</div><div><div class="text-xl font-black uppercase leading-none text-blue-900">PT GAJAH UNGGUL</div><div class="text-xl font-black uppercase leading-none text-blue-900">INTERNATIONAL</div><div class="mt-1 text-xs text-gray-600">Jasa Logistik &amp; Forwarding</div></div></div>
                <div class="col-span-8 text-right"><div class="text-4xl font-black uppercase tracking-wide text-blue-900">PIB</div><div class="mt-1 text-sm font-bold uppercase text-gray-700">Pemberitahuan Impor Barang</div></div>
            </div>

            <div class="mt-4 grid grid-cols-2 gap-4">
                <div class="rounded border border-gray-300 p-3"><div class="mb-2 bg-blue-900 px-2 py-1 text-sm font-bold uppercase text-white">1. Data Importir</div><table class="w-full text-sm"><tr><td class="py-1 pr-2 font-semibold text-gray-600">Nama Importir</td><td class="border-b border-gray-400">:</td><td class="border-b border-gray-400 pl-2">PT Gajah Unggul International</td></tr><tr><td class="py-1 pr-2 font-semibold text-gray-600">NPWP</td><td class="border-b border-gray-400">:</td><td class="border-b border-gray-400 pl-2">12.345.678.9-012.000</td></tr><tr><td class="py-1 pr-2 font-semibold text-gray-600">NIB</td><td class="border-b border-gray-400">:</td><td class="border-b border-gray-400 pl-2">1234567890123</td></tr><tr><td class="py-1 pr-2 font-semibold text-gray-600">Alamat</td><td class="border-b border-gray-400">:</td><td class="border-b border-gray-400 pl-2">Jl. Raya Industri No. 88, Tangerang, Banten, Indonesia</td></tr><tr><td class="py-1 pr-2 font-semibold text-gray-600">Negara</td><td class="border-b border-gray-400">:</td><td class="border-b border-gray-400 pl-2">Indonesia</td></tr><tr><td class="py-1 pr-2 font-semibold text-gray-600">No. Telepon</td><td class="border-b border-gray-400">:</td><td class="border-b border-gray-400 pl-2">(021) 12345678</td></tr><tr><td class="py-1 pr-2 font-semibold text-gray-600">Email</td><td class="border-b border-gray-400">:</td><td class="border-b border-gray-400 pl-2">info@gajahunggul.co.id</td></tr></table></div>
                <div class="rounded border border-gray-300 p-3"><div class="mb-2 bg-blue-900 px-2 py-1 text-sm font-bold uppercase text-white">2. Data Eskpor / Penjual</div><table class="w-full text-sm"><tr><td class="py-1 pr-2 font-semibold text-gray-600">Nama Eksportir</td><td class="border-b border-gray-400">:</td><td class="border-b border-gray-400 pl-2">ABC TRADING CO., LTD</td></tr><tr><td class="py-1 pr-2 font-semibold text-gray-600">Alamat</td><td class="border-b border-gray-400">:</td><td class="border-b border-gray-400 pl-2">1000 Sukhumvit Road, Bangkok 10110</td></tr><tr><td class="py-1 pr-2 font-semibold text-gray-600">Negara Asal</td><td class="border-b border-gray-400">:</td><td class="border-b border-gray-400 pl-2">Thailand</td></tr><tr><td class="py-1 pr-2 font-semibold text-gray-600">No. Telepon</td><td class="border-b border-gray-400">:</td><td class="border-b border-gray-400 pl-2">+66 2 123 4567</td></tr><tr><td class="py-1 pr-2 font-semibold text-gray-600">Email</td><td class="border-b border-gray-400">:</td><td class="border-b border-gray-400 pl-2">info@abctrading.co.th</td></tr></table></div>
            </div>

            <div class="mt-4 rounded border border-gray-300 p-3"><div class="mb-2 bg-blue-900 px-2 py-1 text-sm font-bold uppercase text-white">3. Data Pengangkutan</div><table class="w-full text-sm"><thead class="bg-gray-200 text-gray-800"><tr><th class="border border-gray-300 px-2 py-2 text-left">Nama Kapal / Penberangan</th><th class="border border-gray-300 px-2 py-2 text-left">Voyage / Flight</th><th class="border border-gray-300 px-2 py-2 text-left">Pelabuhan Muat</th><th class="border border-gray-300 px-2 py-2 text-left">Pelabuhan Bongkar</th><th class="border border-gray-300 px-2 py-2 text-left">Tanggal Perkiraan Kedatangan</th><th class="border border-gray-300 px-2 py-2 text-left">Cara Pengangkutan</th></tr></thead><tbody><tr><td class="border border-gray-300 px-2 py-3">MV. OCEAN STAR</td><td class="border border-gray-300 px-2 py-3">OS-0826E</td><td class="border border-gray-300 px-2 py-3">Tanjung Priok, Indonesia</td><td class="border border-gray-300 px-2 py-3">Laem Chabang, Thailand</td><td class="border border-gray-300 px-2 py-3">20 Agustus 2026</td><td class="border border-gray-300 px-2 py-3">CY - Container Yard</td></tr></tbody></table></div>

            <div class="mt-4 overflow-hidden rounded border border-gray-300"><div class="bg-blue-900 px-3 py-2 text-sm font-black uppercase text-white">4. Data Peti Kemas</div><table class="w-full border-collapse text-sm"><thead class="bg-gray-200 text-gray-800"><tr><th class="border border-gray-300 px-2 py-2 text-left">No.</th><th class="border border-gray-300 px-2 py-2 text-left">Nomor Kontainer</th><th class="border border-gray-300 px-2 py-2 text-left">Seal Number</th><th class="border border-gray-300 px-2 py-2 text-left">Ukuran</th><th class="border border-gray-300 px-2 py-2 text-left">Jenis Kontainer</th><th class="border border-gray-300 px-2 py-2 text-left">Tipe Muatan</th><th class="border border-gray-300 px-2 py-2 text-left">Jumlah Paket</th></tr></thead><tbody><tr><td class="border border-gray-300 px-2 py-3 text-center">1</td><td class="border border-gray-300 px-2 py-3">TGHU1234567</td><td class="border border-gray-300 px-2 py-3">SL123456</td><td class="border border-gray-300 px-2 py-3">20 Feet</td><td class="border border-gray-300 px-2 py-3">Dry Container</td><td class="border border-gray-300 px-2 py-3">General Cargo</td><td class="border border-gray-300 px-2 py-3">100</td></tr></tbody></table></div>

            <div class="mt-4 overflow-hidden rounded border border-gray-300"><div class="bg-blue-900 px-3 py-2 text-sm font-black uppercase text-white">5. Data Barang Impor</div><table class="w-full border-collapse text-sm"><thead class="bg-gray-200 text-gray-800"><tr><th class="border border-gray-300 px-2 py-2 text-left">No.</th><th class="border border-gray-300 px-2 py-2 text-left">Nama Barang / Uraian Barang</th><th class="border border-gray-300 px-2 py-2 text-left">HS Code</th><th class="border border-gray-300 px-2 py-2 text-left">Negara Asal</th><th class="border border-gray-300 px-2 py-2 text-left">Jumlah</th><th class="border border-gray-300 px-2 py-2 text-left">Satuan</th><th class="border border-gray-300 px-2 py-2 text-left">Berat Bersih (KG)</th><th class="border border-gray-300 px-2 py-2 text-left">Nilai CIF (USD)</th></tr></thead><tbody><tr><td class="border border-gray-300 px-2 py-3 text-center">1</td><td class="border border-gray-300 px-2 py-3">MESIN PRODUKSI MODEL XYZ</td><td class="border border-gray-300 px-2 py-3">8479.82.00</td><td class="border border-gray-300 px-2 py-3">Thailand</td><td class="border border-gray-300 px-2 py-3">2</td><td class="border border-gray-300 px-2 py-3">Unit</td><td class="border border-gray-300 px-2 py-3">2,500</td><td class="border border-gray-300 px-2 py-3">30,500.00</td></tr></tbody></table></div>

            <div class="mt-4 grid grid-cols-[1.2fr_1fr] gap-4">
                <div class="rounded border border-gray-300 p-3"><div class="mb-2 bg-blue-900 px-2 py-1 text-sm font-bold uppercase text-white">6. Rincian Nilai Impor</div><div class="space-y-2 text-sm text-gray-700"><div class="flex justify-between"><span>Nilai CIF</span><span>30,500.00 USD</span></div><div class="flex justify-between"><span>Freight</span><span>350.00 USD</span></div><div class="flex justify-between"><span>Insurance</span><span>150.00 USD</span></div><div class="flex justify-between"><span>Nilai Lainnya</span><span>0.00 USD</span></div><div class="mt-2 flex justify-between border-t border-gray-300 pt-2 font-bold text-gray-900"><span>TOTAL NILAI IMPOR (CIF)</span><span>31,000.00 USD</span></div></div></div>
                <div class="rounded border border-gray-300 p-3"><div class="mb-2 bg-blue-900 px-2 py-1 text-sm font-bold uppercase text-white">7. Dokumen Pendukung</div><table class="w-full text-sm"><tr><td class="py-1 pr-2 font-semibold text-gray-600">Bill of Lading</td><td class="border-b border-gray-400">:</td><td class="border-b border-gray-400 pl-2">BL/GUI/2026/0001</td></tr><tr><td class="py-1 pr-2 font-semibold text-gray-600">Invoice</td><td class="border-b border-gray-400">:</td><td class="border-b border-gray-400 pl-2">INV/GUI/2026/0001</td></tr><tr><td class="py-1 pr-2 font-semibold text-gray-600">Packing List</td><td class="border-b border-gray-400">:</td><td class="border-b border-gray-400 pl-2">PL/GUI/2026/0001</td></tr><tr><td class="py-1 pr-2 font-semibold text-gray-600">PIB</td><td class="border-b border-gray-400">:</td><td class="border-b border-gray-400 pl-2">PIB/GUI/2026/0001</td></tr></table></div>
            </div>
            </div>
            <div class="mx-auto max-w-6xl bg-gray-100 px-6 py-4 flex gap-3 border-t border-gray-300 rounded-b-2xl">
                <button type="submit" class="rounded-xl bg-red-600 px-6 py-2.5 text-sm font-semibold text-white shadow-sm transition hover:bg-red-700">Simpan Dokumen</button>
                <button type="reset" class="rounded-xl border border-gray-300 bg-white px-6 py-2.5 text-sm font-semibold text-gray-700 transition hover:bg-gray-50">Reset</button>
                <a href="{{ route('format.index') }}" class="rounded-xl border border-gray-300 bg-white px-6 py-2.5 text-sm font-semibold text-gray-700 transition hover:bg-gray-50">Batal</a>
            </div>
        </form>
    </div>
</x-app-layout>
